# YAML Configuration file for ninjin.github.com

auto:       true
markdown:   maruku
permalink:  date
pygments:   true
safe:       true
server:     true

exclude: CNAME, LICENSE, README.md, bibtex_icon.svg, build
